### ISSUE TITLE
Option to disable recent saving/list?

### ISSUE THREAD

**Issue by 60fpshacksrock** [emukidid/swiss-gc#553]
Just wondering about an option to disable the recent list and it saving upon every game boot.

**Comment by emukidid** [comment]
May I ask why you'd want to disable it? Is your swiss.ini rather huge and saving the recent list takes a while? If so issue #513 should solve that.

**Comment by 60fpshacksrock** [comment]
No problems with it. 

Though the less writes to it the better. I hear SD cards have a lesser life span (number of writes) that USB drives.

**Comment by emukidid** [comment]
There are some code paths to prevent unnecessary writes, such as if you're launching the same game over and over again etc, but there'll be far less writes when config is split up (and I guess I can make it optional at that point too).

**Comment by 60fpshacksrock** [comment]
Thank you. And great program by the way.

Not only is game loading faster than ever, but now memory cars emulation is back and working better than ever.

I had a question about memory card emulation. I noticed it saves much faster than a real memory card does. If you decide
to slow it down to be more accurate because of compatibility issue, can we still have an option to use fast saving?

**Comment by emukidid** [comment]
Added in 50c7cdb4a32e49131d365396987589baa93ecc8a. You can turn it off completely or set it to a "lazy" mode where it will only add new entries and it won't save for a simple reshuffle (if you constantly only use a top 8 list of entries etc).
